### ISSUE TITLE
Tuning cap property is assymetric

### ISSUE THREAD

**Issue by fourstix** [fourstix/Sparkfun_CircuitPython_QwiicAS3935#1]
The tune_cap property receives a value from 0-15, but turns the reg value 0-15 multiplied by 8pf.  This means code such as 

save_value = lightning.tune_cap  # say the value is 8pf for a register value of 1
//
lightning.tune_cap = save_value  # Will set the capacitor value to 8 * 8 or 64pf instead of 8pf.

Fix change tune_cap setter to take 0 - 120 and integer divide by 8, update doc comments and example 3 code as appropriate.

**Comment by fourstix** [comment]
@edspark Any thoughts as author of the original code? 
I think this is the most user-friendly way to port it. 

In the Aruduino code there are two different named methods so this difference in values isn't a big deal.  In python it becomes a property, and the getter/setter methods should return and take the same values.

**Comment by edspark** [comment]
I'm in the original author of the code; I'm not so stoked on some of my design choices. You're making absolute sense @fourstix, what a user gives the library should be what they get in return. Actually giving the pF value to the function as argument makes a lot more sense than abstracting it to a random integer. I'll have some time early next week - Monday/Tuesday to fix that and perhaps shorten this long mask list.

**Comment by edspark** [comment]
Also thank you very much for you SparkFun/Circuit Python contributions! Let me know if there's something else I can help with.

**Comment by fourstix** [comment]
@edspark Thank you for your feedback! I really appreciate it.  I made the change to return / set the tune_cap in pF values.

**Comment by fourstix** [comment]
Change branch merged into the code, built and released.
