### ISSUE TITLE
Typo in example1_basic_lightning_spi.py

### ISSUE THREAD

**Issue by lightmaster** [fourstix/Sparkfun_CircuitPython_QwiicAS3935#4]
In the basic lightning SPI example, on line 60, its written as

https://github.com/fourstix/Sparkfun_CircuitPython_QwiicAS3935/blob/0bc17ea692e702998062f839929224192c63a502/examples/example1_basic_lightning_spi.py#L60

but should be 
`value += 1`

**Comment by fourstix** [comment]
Good catch!  Thank you.  It's now fixed, but I have to update the build to the new process to publish the update.
