### ISSUE TITLE
On Raspberry Pi AS3935 CS cannot be linked to board.CE0

### ISSUE THREAD

**Issue by tvoverbeek** [fourstix/Sparkfun_CircuitPython_QwiicAS3935#5]
Because of the special read protocol (CS has to go HIGH-LOW-HIGH at the end of a read, lines 638-642 in sparkfun_qwiicas3935.py) the normal SPI0.0 CS of the PIi (board.CE0) cannot be used.
You have to use a normal GPIO for the AS3935 CS. I used GPIO25, board.D25 (which is just above CE0 on the 40-pin connector). 
Then it works on the Pi.

**Comment by fourstix** [comment]
Interesting.  D25 isn't available on the Sparkfun Pi Hat, so I'll set it up on D20.  The CS can be any unused GPIO pin.
