### ISSUE TITLE
Add this to the Community_Bundle or a sparkfun bundle

### ISSUE THREAD

**Issue by tannewt** [fourstix/Sparkfun_CircuitPython_QwiicAS3935#7]
https://github.com/adafruit/CircuitPython_Community_Bundle/tree/master/libraries/drivers

This wasn't discoverable so there is a second library for this sensor here: https://github.com/BiffoBear/CircuitPython_AS3935

**Comment by fourstix** [comment]
Ah, thanks, I'll add it to the Community bundle

**Comment by fourstix** [comment]
This library is specific to the Sparkfun Qwiic AS3935 adapter

**Comment by fourstix** [comment]
Hi @tannewt,

I checked and it looks like it was added 2 years ago. I'm not sure why it's not discoverable.
Here's a screen shot:
![qwiicas3935_community_bundle](https://user-images.githubusercontent.com/5274281/141536319-f9288c93-bc8d-47d0-aed9-b1edd2fb2941.jpg)

If I try to add the submodule again I get this error message:
'libraries/drivers/qwiicas3935' already exists in the index

**Comment by fourstix** [comment]
Confirmed this was done.
